### PR TITLE
UTCT-24: UTC Branding on front and back ends

### PR DESCRIPTION
**Pull request by UTCGilligan**
This has been applied to https://gotest.utc.edu, so please have a look.

- [x] Pending a fix for some backend styling issues #24 
- [x] Pending font change #47 
- [x] Pending revised logo/wordmark #48

## Screenshots:

Screenshot 2023-12-18 at 13 15 02
Screenshot 2023-12-18 at 13 14 51
Screenshot 2023-12-18 at 13 14 48
Screenshot 2023-12-18 at 13 14 42

### CODE REVIEW

**Review by UTCGilligan — COMMENTED** [review]
Looks good:
- Power C
- UTCentric frontend words

**Review by stevendshelton — APPROVED** [review]
Looks great!

**Comment by UTCbridget** [comment]
I love it, but just curious, are we allowed to cut the power c in half in the background?

**Comment by UTCGilligan** [comment]
@bridget, IDK but it can be moved up or down if required. It's just using the default positioning of the default logo.

**Comment by UTCbridget** [comment]
So, I did verify... the Power C is not allowed to be on a background that bisects it for brand compliance. Also, it was requested that the whole horizontal logo be presented above the white field, not just the power C. Otherwise, I think it looks FANTASTIC!

**Comment by UTCGilligan** [comment]
- [ ] Steve Rumbaugh requests we use the full UTC Wordmark, in the dark blue area above the white form.

**Review by UTCGilligan — COMMENTED** [review]
Looks good!
- Frontend styles and assets to stylize for UTC
- Backend styles and assets to stylize for UTC

**Review by UTCbridget — APPROVED** [review]
Great work, Chris and team!

**Review by UTCGilligan — COMMENTED** [review]
Looks good!

**Pull request merged**
